global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nutritioncore'
    metrics_path: /metrics
    static_configs:
      - targets: ['nutritioncore:9090']   # порт внутри контейнера

  - job_name: 'usercore'
    metrics_path: /metrics
    static_configs:
      - targets: ['usercore:5005']       # порт внутри контейнера